sonar.projectKey=taskmanager-api
sonar.projectName=Task Manager API
sonar.projectVersion=1.0
sonar.sources=src
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=node_modules/**,coverage/**,data/**
sonar.test.inclusions=tests/**/*.test.js